---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: copy settings
  template: src=settings_local.py dest={{ project_path }}/settings_local.py

- name: Make Django app migrations
  #become: no
  django_manage: command="makemigrations --noinput" app_path="{{ project_path }}" virtualenv="{{ virtualenv_path }}"
  tags: django.migrate

- name: Run Django app migrations
  become: no
  django_manage: command=migrate app_path="{{ project_path }}" virtualenv="{{ virtualenv_path }}"
  tags: django.migrate


- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic
